In [102]:

import torch
import torch.optim as optim
import torch.nn as nn
import numpy as np
import math
import matplotlib.pyplot as plt
import pandas as pd
n=20
w=torch.randn(n,n, device='cpu', requires_grad=True,dtype=torch.float)
ze = pd.DataFrame({'Value': torch.from_numpy(np.absolute(np.array(np.random.normal(0, 1, 10)))),
                    'Type': 'E',
                    'sign': np.array([1] * 10, dtype='int32')})    


zi = pd.DataFrame({'Value': torch.from_numpy(-np.absolute(np.array(np.random.normal(0, 1, 10)))),
                    'Type': 'I',
                    'sign': np.array([-1] * 10, dtype='int32')})    

zf = pd.concat([ze, zi])
zd = zf.sample(frac=1).reset_index(drop=True)
z=torch.randn(1,20)
print (z,z[:,1])



for a in range(19):
    #print (zd.loc[a,'Value'])
    z[:a]=(zd.loc[a,'Value'])
        
#print (z,zd)

for i in range(19):
    for j in range(19):
        #print (zd.loc[j,'sign'])
        #print (w[i,j])
        w[i,j]=(zd.loc[j,'sign'])*w[i,j]
        #print (w[i,j])
        
        




tensor([[ 1.6811, -0.9059,  0.3573, -0.4640,  0.1727,  2.2083,  1.0390,  1.2040,
          0.7376, -0.0707,  0.8545,  0.8118, -0.5464, -0.1826, -0.8850, -2.0146,
          0.9651, -1.0944,  0.8438, -0.6582]]) tensor([-0.9059])


In [94]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print (x[2])

2


In [80]:
n=3
w=torch.randn(n,n, device='cpu', requires_grad=True,dtype=torch.float)
print (w,w[1,2])

tensor([[-1.0010,  0.2334, -1.3192],
        [-0.9127, -0.3163, -0.0831],
        [ 1.0572, -0.4791,  0.2192]], requires_grad=True) tensor(-0.0831, grad_fn=<SelectBackward>)


In [26]:
print (np.random.normal(0, 1, 3))

[-2.49183218 -2.19528405  0.68307422]


In [56]:
print (ze,ze.iloc(1))

       Value Type
0  -1.320661    I
1   0.906878    E
2   0.223871    E
3   0.259332    E
4   0.084434    E
5  -0.977689    I
6  -2.386828    I
7  -0.713555    I
8  -1.419269    I
9  -0.407654    I
10  0.011105    E
11 -0.916832    I
12  0.523302    E
13  1.778927    E
14 -0.858458    I
15  2.553070    E
16 -0.105432    I
17  0.665925    E
18  0.584413    E
19 -0.144292    I <pandas.core.indexing._iLocIndexer object at 0x11a8bb2c8>
